<<<<<<< HEAD
// components/Layout.tsx
'use client';

import React from 'react';
import Header from './header'; // Import your Header
import Footer from './footer'; // Import your Footer
import { SessionProvider } from 'next-auth/react';

// Define the shape of props your Layout component expects
interface LayoutProps {
  children: React.ReactNode; // This means it expects any renderable React content
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    // This div ensures your layout takes at least the full screen height
    // and stacks header, main, and footer vertically.
    <SessionProvider>
      <div className="grid grid-cols-6 grid-rows-12 min-h-screen grid-auto-rows-fr">
        <Header />
        <main className="col-span-full row-start-2 row-end-12 grid grid-cols-6">
          {children}
        </main>
        <Footer />
      </div>
    </SessionProvider>
  );
};

export default Layout;
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <a href="/">Home</a>
          <a href="/users">Users</a>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
>>>>>>> feature/user
